import type { AppState, Product } from "./types";

const now = Date.now();

const seedProducts = (): Product[] => [
  {
    id: "p1",
    shopId: "s1",
    companyId: "c1",
    name: "Golden Penny Rice 25kg",
    barcode: "8901234567890",
    sku: "GPR-25",
    category: "Grains & Staples",
    unit: "bag",
    price: 48500,
    stock: 42,
    notes: "Parboiled long grain",
    updatedAt: now,
  },
  {
    id: "p2",
    shopId: "s1",
    companyId: "c1",
    name: "Mama Gold Semovita 10kg",
    barcode: "8901234567891",
    sku: "MGS-10",
    category: "Grains & Staples",
    unit: "bag",
    price: 12800,
    stock: 30,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p3",
    shopId: "s1",
    companyId: "c1",
    name: "Dangote Sugar 50kg",
    barcode: "8901234567892",
    sku: "DGS-50",
    category: "Grains & Staples",
    unit: "bag",
    price: 72000,
    stock: 18,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p4",
    shopId: "s1",
    companyId: "c1",
    name: "Kings Vegetable Oil 5L",
    barcode: "8901234567893",
    sku: "KVO-5",
    category: "Oils & Condiments",
    unit: "bottle",
    price: 9800,
    stock: 55,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p5",
    shopId: "s1",
    companyId: "c1",
    name: "Devon King's Oil 3L",
    barcode: "8901234567894",
    sku: "DKO-3",
    category: "Oils & Condiments",
    unit: "bottle",
    price: 6400,
    stock: 40,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p6",
    shopId: "s1",
    companyId: "c1",
    name: "Maggi Star Cubes 400g",
    barcode: "8901234567895",
    sku: "MSC-400",
    category: "Oils & Condiments",
    unit: "pack",
    price: 2150,
    stock: 80,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p7",
    shopId: "s1",
    companyId: "c1",
    name: "Indomie Chicken 70g x 40",
    barcode: "8901234567896",
    sku: "IND-40",
    category: "Grains & Staples",
    unit: "carton",
    price: 8900,
    stock: 64,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p8",
    shopId: "s2",
    companyId: "c1",
    name: "Peak Milk Powder 400g",
    barcode: "8901234567897",
    sku: "PMK-400",
    category: "Beverages",
    unit: "tin",
    price: 3450,
    stock: 36,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p9",
    shopId: "s2",
    companyId: "c1",
    name: "Bournvita 500g",
    barcode: "8901234567898",
    sku: "BVT-500",
    category: "Beverages",
    unit: "tin",
    price: 4200,
    stock: 22,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p10",
    shopId: "s2",
    companyId: "c1",
    name: "Always Ultra 16 pads",
    barcode: "8901234567899",
    sku: "ALU-16",
    category: "Personal Care",
    unit: "pack",
    price: 2650,
    stock: 28,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p11",
    shopId: "s2",
    companyId: "c1",
    name: "Omo Detergent 900g",
    barcode: "8901234567800",
    sku: "OMO-900",
    category: "Household",
    unit: "pack",
    price: 1850,
    stock: 70,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p12",
    shopId: "s3",
    companyId: "c2",
    name: "Hypo Bleach 1L",
    barcode: "8901234567801",
    sku: "HYP-1",
    category: "Household",
    unit: "bottle",
    price: 1450,
    stock: 33,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p13",
    shopId: "s3",
    companyId: "c2",
    name: "Tomatoes (local) 1kg",
    barcode: "LOC-TOM-1",
    sku: "TOM-1",
    category: "Fresh Produce",
    unit: "kg",
    price: 1800,
    stock: 12,
    notes: "Price may vary daily",
    updatedAt: now,
  },
  {
    id: "p14",
    shopId: "s3",
    companyId: "c2",
    name: "Onions 1kg",
    barcode: "LOC-ONI-1",
    sku: "ONI-1",
    category: "Fresh Produce",
    unit: "kg",
    price: 1400,
    stock: 20,
    notes: "",
    updatedAt: now,
  },
  {
    id: "p15",
    shopId: "s3",
    companyId: "c2",
    name: "Coca-Cola PET 50cl x 12",
    barcode: "8901234567802",
    sku: "COK-12",
    category: "Beverages",
    unit: "pack",
    price: 3600,
    stock: 48,
    notes: "",
    updatedAt: now,
  },
];

export function createSeedState(): AppState {
  return {
    companies: [
      {
        id: "c1",
        name: "Hauwa Retail Nigeria",
        code: "HRN",
        city: "Kano",
        status: "active",
        createdAt: now - 86400000 * 120,
      },
      {
        id: "c2",
        name: "Mohammed Foods Distribution",
        code: "MFD",
        city: "Abuja",
        status: "active",
        createdAt: now - 86400000 * 90,
      },
      {
        id: "c3",
        name: "HM Market Partners",
        code: "HMP",
        city: "Lagos",
        status: "paused",
        createdAt: now - 86400000 * 40,
      },
    ],
    shops: [
      {
        id: "s1",
        companyId: "c1",
        name: "HM Central Market",
        code: "HRN-01",
        address: "Shop 14, Sabon Gari Market",
        city: "Kano",
        status: "open",
        createdAt: now - 86400000 * 100,
      },
      {
        id: "s2",
        companyId: "c1",
        name: "HM Naibawa Outlet",
        code: "HRN-02",
        address: "Plot 8, Zaria Road",
        city: "Kano",
        status: "open",
        createdAt: now - 86400000 * 70,
      },
      {
        id: "s3",
        companyId: "c2",
        name: "MFD Wuse Shop",
        code: "MFD-01",
        address: "Wuse Zone 3, Shop 22",
        city: "Abuja",
        status: "open",
        createdAt: now - 86400000 * 60,
      },
      {
        id: "s4",
        companyId: "c2",
        name: "MFD Garki Depot Counter",
        code: "MFD-02",
        address: "Area 1, Garki",
        city: "Abuja",
        status: "closed",
        createdAt: now - 86400000 * 30,
      },
    ],
    products: seedProducts(),
    users: [
      {
        id: "u1",
        name: "Hauwa Mohammed",
        email: "org@hauwa.ng",
        password: "admin123",
        role: "org_admin",
      },
      {
        id: "u2",
        name: "Amina Bello",
        email: "company@hauwa.ng",
        password: "company123",
        role: "company_admin",
        companyId: "c1",
      },
      {
        id: "u3",
        name: "Ibrahim Yusuf",
        email: "mfd@hauwa.ng",
        password: "company123",
        role: "company_admin",
        companyId: "c2",
      },
      {
        id: "u4",
        name: "Fatima Sani",
        email: "shop@hauwa.ng",
        password: "shop123",
        role: "shop_manager",
        companyId: "c1",
        shopId: "s1",
      },
      {
        id: "u5",
        name: "Musa Abdullahi",
        email: "naibawa@hauwa.ng",
        password: "shop123",
        role: "shop_manager",
        companyId: "c1",
        shopId: "s2",
      },
    ],
    history: [
      {
        id: "h1",
        at: now - 86400000 * 3,
        productId: "p1",
        shopId: "s1",
        name: "Golden Penny Rice 25kg",
        oldPrice: 46000,
        newPrice: 48500,
        changedBy: "Fatima Sani",
      },
      {
        id: "h2",
        at: now - 86400000,
        productId: "p4",
        shopId: "s1",
        name: "Kings Vegetable Oil 5L",
        oldPrice: 9200,
        newPrice: 9800,
        changedBy: "Fatima Sani",
      },
      {
        id: "h3",
        at: now - 86400000 * 2,
        productId: "p13",
        shopId: "s3",
        name: "Tomatoes (local) 1kg",
        oldPrice: 1600,
        newPrice: 1800,
        changedBy: "Ibrahim Yusuf",
      },
    ],
    recent: [],
  };
}

export const STORAGE_KEY = "hm-price-checker-v2";
export const SESSION_KEY = "hm-price-session-v2";
